### ISSUE TITLE
Deploy application on neetoDeploy

### ISSUE THREAD

**Issue by vysakh-poulose** [vysakh-poulose/neeto-ui-challenge-by-vysakh-poulose#9]

**Comment by vysakh-poulose** [comment]
Deployed on [neeto-ui-challenge.neetoreviewapp.net/](https://neeto-ui-challenge.neetoreviewapp.net/)

**Comment by navaneethsdk** [comment]
@vysakh-poulose  a few comments:
- [x] Let's add `is` prefix to boolean variables. https://github.com/vysakh-poulose/neeto-ui-challenge-by-vysakh-poulose/blob/ba6c457961d652bdaee70c3a05563e60358963cd/app/javascript/src/components/Dashboard/Notes/index.jsx#L20
- [x] Let's not abbreviations. I think it would be better to use the `event` keyword. https://github.com/vysakh-poulose/neeto-ui-challenge-by-vysakh-poulose/blob/ba6c457961d652bdaee70c3a05563e60358963cd/app/javascript/src/components/Dashboard/Notes/index.jsx#L65 https://github.com/vysakh-poulose/neeto-ui-challenge-by-vysakh-poulose/blob/ba6c457961d652bdaee70c3a05563e60358963cd/app/javascript/src/components/Dashboard/Contacts/Header.jsx#L28
- [x] Let's move this URL to constants file. https://github.com/vysakh-poulose/neeto-ui-challenge-by-vysakh-poulose/blob/ba6c457961d652bdaee70c3a05563e60358963cd/app/javascript/src/components/Dashboard/Notes/Card.jsx#L48

Rest of the app LGTM.
